<a href="https://colab.research.google.com/github/AbuzarMohd/prime_course/blob/ML/Naive_Bayes_KNN_CV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv('/content/drive/MyDrive/AI Engineer Course by Apna College/datasets/heart.csv')
df.head()

   age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [3]:
X = df.drop('target', axis=1)
y = df['target']

In [5]:
X.head()

   age  sex  cp  trestbps  chol  fbs  ...  thalach  exang  oldpeak  slope  ca  thal
0   63    1   3       145   233    1  ...      150      0      2.3      0   0     1
1   37    1   2       130   250    0  ...      187      0      3.5      0   0     2
2   41    0   1       130   204    0  ...      172      0      1.4      2   0     2
3   56    1   1       120   236    0  ...      178      0      0.8      2   0     2
4   57    0   0       120   354    0  ...      163      1      0.6      2   0     2

[5 rows x 13 columns]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=45)

In [10]:
# Naive Bayes
gnb_model = GaussianNB()
gnb_model.fit(X_train, y_train)

GaussianNB()

In [11]:
y_pred = gnb_model.predict(X_test)

In [12]:
#Evaluation

print("The recall score: ", recall_score(y_test, y_pred))
print("The accuracy score: ", accuracy_score(y_test, y_pred))
print("The precision score: ", precision_score(y_test, y_pred))

The recall score:  0.7894736842105263
The accuracy score:  0.819672131147541
The precision score:  0.9090909090909091

# KNN Model

In [15]:
X = df.drop('target', axis=1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=45)

scaler = StandardScaler()
X_tarin_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [16]:
X_tarin_scaled

array([[-1.71052151,  0.71589105, -0.90431483, ..., -0.63998064,
        -0.71122725,  1.17665296],
       [-2.15206413,  0.71589105, -0.90431483, ..., -0.63998064,
        -0.71122725,  1.17665296],
       [ 0.27642028,  0.71589105,  0.06832601, ...,  1.02534533,
         0.23969537, -0.46930089],
       ...,
       [-0.16512234,  0.71589105, -0.90431483, ...,  1.02534533,
        -0.71122725,  1.17665296],
       [-1.15859324,  0.71589105,  0.06832601, ...,  1.02534533,
        -0.71122725, -0.46930089],
       [-0.60666496, -1.39686059,  0.06832601, ..., -0.63998064,
        -0.71122725, -0.46930089]])

In [17]:
knn_classifier = KNeighborsClassifier(n_neighbors=3)
knn_classifier.fit(X_tarin_scaled, y_train)

KNeighborsClassifier(n_neighbors=3)

In [23]:
y_pred_knn = knn_classifier.predict(X_test_scaled)
#Evaluation for k= 3

print("The recall score: ", recall_score(y_test, y_pred_knn))
print("The accuracy score: ", accuracy_score(y_test, y_pred_knn))
print("The precision score: ", precision_score(y_test, y_pred_knn))

The recall score:  0.7894736842105263
The accuracy score:  0.7868852459016393
The precision score:  0.8571428571428571

In [24]:
knn_classifier = KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(X_tarin_scaled, y_train)

KNeighborsClassifier()

In [25]:
y_pred_knn = knn_classifier.predict(X_test_scaled)
#Evaluation for k= 5

print("The recall score: ", recall_score(y_test, y_pred_knn))
print("The accuracy score: ", accuracy_score(y_test, y_pred_knn))
print("The precision score: ", precision_score(y_test, y_pred_knn))

The recall score:  0.9210526315789473
The accuracy score:  0.8852459016393442
The precision score:  0.8974358974358975

In [26]:
knn_classifier = KNeighborsClassifier(n_neighbors=7)
knn_classifier.fit(X_tarin_scaled, y_train)

KNeighborsClassifier(n_neighbors=7)

In [28]:
y_pred_knn = knn_classifier.predict(X_test_scaled)
#Evaluation for k= 7

print("The recall score: ", recall_score(y_test, y_pred_knn))
print("The accuracy score: ", accuracy_score(y_test, y_pred_knn))
print("The precision score: ", precision_score(y_test, y_pred_knn))

The recall score:  0.8947368421052632
The accuracy score:  0.8852459016393442
The precision score:  0.918918918918919

In [41]:
# Cross Validation for hyperparam tuning using GridSearchCV
from sklearn.model_selection import GridSearchCV

classifier = KNeighborsClassifier()
param_grid = {"n_neighbors": [3,5,7,9,11,13,15,17,19]}

classifierCV = GridSearchCV(classifier, param_grid, cv=5, scoring="recall")

classifierCV.fit(X_tarin_scaled, y_train)

y_pred_CV = classifierCV.predict(X_test_scaled)
#Evaluation for classifierCV

print("The recall score: ", recall_score(y_test, y_pred_CV))
print("The accuracy score: ", accuracy_score(y_test, y_pred_CV))
print("The precision score: ", precision_score(y_test, y_pred_CV))

results =pd.DataFrame(classifierCV.cv_results_)
print(results[['param_n_neighbors', 'mean_test_score']])
print(classifierCV.best_params_)

The recall score:  0.8421052631578947
The accuracy score:  0.819672131147541
The precision score:  0.8648648648648649
   param_n_neighbors  mean_test_score
0                  3         0.865231
1                  5         0.857846
2                  7         0.865231
3                  9         0.888923
4                 11         0.920615
5                 13         0.904923
6                 15         0.928308
7                 17         0.952000
8                 19         0.944000
{'n_neighbors': 17}

In [46]:
# Pipeline
from sklearn.pipeline import Pipeline
df = pd.read_csv('/content/drive/MyDrive/AI Engineer Course by Apna College/datasets/heart.csv')

X = df.drop('target', axis=1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=45)

pipeline = Pipeline([('scaler', StandardScaler()), ('knn', KNeighborsClassifier())])

param_grid = {"knn__n_neighbors": [3,5,7,9,11,13,15,17,19]}

classifierCV = GridSearchCV(pipeline, param_grid, cv=5, scoring="recall")

classifierCV.fit(X_train, y_train)

y_pred_CV = classifierCV.predict(X_test)
#Evaluation for classifierCV

print("The recall score: ", recall_score(y_test, y_pred_CV))
print("The accuracy score: ", accuracy_score(y_test, y_pred_CV))
print("The precision score: ", precision_score(y_test, y_pred_CV))

results =pd.DataFrame(classifierCV.cv_results_)
print(classifierCV.best_params_)

The recall score:  0.8421052631578947
The accuracy score:  0.819672131147541
The precision score:  0.8648648648648649
{'knn__n_neighbors': 17}